#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#home_index:
# path: /home
#  controller: App\Controller\HomeController::index

author-login-check:
  path: /author-login-check

admin-login-check:
  path: /admin-login-check

logout:
  path: /logout
